# The length of the hash used to identify a parameter combination
hash_length: 7

# If true, use Singularity instead of Docker
# Singularity support is only available on Unix
singularity: false

algorithms: 
  - 
    name: pathlinker
    params: 
      directed: true
      include: true
      run1: 
        k: 
          - 5
          - 10
  - 
    name: omicsintegrator1
    params: 
      directed: false
      include: true
      run1: 
        b: 
          - 1
        d: 
          - 10
        g: 
          - 3
        r: 
          - 5
        w: 
          - 5
  - 
    name: omicsintegrator2
    params: 
      directed: false
      include: false
      run1: 
        b: 
          - 4
        g: 
          - 0
      run2: 
        b: 
          - 2
        g: 
          - 3
  - 
    name: meo
    params: 
      directed: true
      include: false
      run1: 
        local_search: 
          - "Yes"
        max_path_length: 
          - 3
        rand_restarts: 
          - 10
datasets: 
  - 
    data_dir: input
    edge_files: 
      - phosphosite-irefindex13.0-uniprot.txt
    label: tps-egfr
    node_files: 
      - tps-egfr-prizes.txt
    other_files: []
reconstruction_settings: 
  locations: 
    reconstruction_dir: output/egfr
  run: true
analysis: 
  graphspace: 
    include: false
  summary: 
    include: true
